example_simple_weather:
  resources_servers:
    example_simple_weather:
      entrypoint: app.py
      domain: agent
      description: Basic single-step tool calling
simple_weather_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: simple_weather
      model_server:
        type: responses_api_models
        name: policy_model
      datasets:
      - name: example
        type: example
        jsonl_fpath: resources_servers/example_simple_weather/data/example.jsonl
