stateful_counter_resources_server:
  resources_servers:
    stateful_counter:
      entrypoint: app.py
stateful_counter_simple_agent:
  responses_api_agents:
    simple_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: stateful_counter_resources_server
      model_server:
        type: responses_api_models
        name: openai_model
      datasets:
      - name: train
        type: train
        jsonl_fpath: resources_servers/stateful_counter/data/train.jsonl
        gitlab_identifier:
          dataset_name: stateful_counter
          version: 0.0.1
          artifact_fpath: train.jsonl
        license: Apache 2.0
      - name: validation
        type: validation
        jsonl_fpath: resources_servers/stateful_counter/data/validation.jsonl
        gitlab_identifier:
          dataset_name: stateful_counter
          version: 0.0.1
          artifact_fpath: validation.jsonl
        license: Apache 2.0
      - name: example
        type: example
        jsonl_fpath: resources_servers/stateful_counter/data/example.jsonl
